config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # devise_for :users //before
    devise_for :users, controllers: {
      confirmations: "users/confirmations",
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      unlocks: "users/unlocks"
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'top#index'
    resources :users, only: [:show, :edit, :update] do
      member do
        get 'mypage'
      end
    end
    resources :blogs,  only: [:index, :new, :create, :destroy, :edit, :update, :show] do
      collection do
        get 'search'
      end
      collection do
        get 'topmap'
      end
      collection do
        get 'adminpage'
      end
      member do
        get 'detailpage'
      end
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
    resources :journals, only: [:new, :create, :destroy, :edit, :update, :show]
    resources :notifications, only: [:create, :destroy]
end

app/models/blog.rb
class Blog < ApplicationRecord
    is_impressionable counter_cache: true  #PV数確認のために実装したが、エラー発生により使用中止
    after_create :create_feed_content
    validates :title, presence: true
    enum status: { draft: 0, published: 1}
    
    enum excellent: { normal: 0, excellent: 1}
    
    has_many :blog_photos, foreign_key: :blog_id, dependent: :destroy
    accepts_nested_attributes_for :blog_photos, allow_destroy: true, reject_if: proc { |attributes| attributes['photo'].blank? }
    
    has_many :blog_images, foreign_key: :blog_id, dependent: :destroy
    accepts_nested_attributes_for :blog_images, allow_destroy: true, reject_if: proc { |attributes| attributes['image'].blank? }
    
    belongs_to :user
    has_one :feed_content, as: :content, dependent: :destroy
    
    has_many :likes
    has_many :liked_users, through: :likes, source: :user, dependent: :destroy
    
    has_many :blog_feelings, dependent: :destroy
    has_many :emotions, through: :blog_feelings
    accepts_nested_attributes_for :blog_feelings, allow_destroy: true
    
    has_many :blog_topics, dependent: :destroy
    has_many :themes, through: :blog_topics
    accepts_nested_attributes_for :blog_topics, allow_destroy: true
    
    has_many :comments, dependent: :destroy
    
    has_many :notifications, dependent: :destroy

    def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and blog_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
        if temp.blank?
          notification = current_user.active_notifications.new(
            blog_id: id,
            visited_id: user_id,
            action: 'like'
          )
          # 自分の投稿に対するいいねの場合は、通知済みとする
          if notification.visitor_id == notification.visited_id
            notification.checked = true
          end
          notification.save if notification.valid?
        end
    end
    
    def create_notification_comment!(current_user, comment_id)
        # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
        temp_ids = Comment.select(:user_id).where(blog_id: id).where.not(user_id: current_user.id).distinct
        temp_ids.each do |temp_id|
          save_notification_comment!(current_user, comment_id, temp_id['user_id'])
        end
        # まだ誰もコメントしていない場合は、投稿者に通知を送る
        save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
    end

    def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
        notification = current_user.active_notifications.new(
          blog_id: id,
          comment_id: comment_id,
          visited_id: visited_id,
          action: 'comment'
        )
        # 自分の投稿に対するコメントの場合は、通知済みとする
        if notification.visitor_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
    end

    private
    def create_feed_content
        self.feed_content = FeedContent.create(user_id: user_id, updated_at: updated_at)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    impressionist :actions=> [:detailpage] #PV数実装のため。現在は外す。
    # before_action :move_to_index
    def index
        @blogs = Blog.order("created_at DESC").page(params[:page]).per(5)
    end
    
    def adminpage
        @blogs = Blog.all
    end
    
    def detailpage
        @blog = Blog.find(params[:id])
        @like = Like.new
        @blog_photos = @blog.blog_photos.all
        @blog_images = @blog.blog_images.all
        @comments = @blog.comments
        # impressionist(@blog, nil, unique: [session_url: session_url.to_s])  #PV数確認のために実装を試みたが、謎のエラーにより外した
        impressionist(@blog, nil, unique: [:ip_address]) 
    end
    
    def topmap
        @blogkanagawas = Blog.order("created_at DESC").where(status: 'published').joins(:user).where("users.prefecture = ?","神奈川").limit(1)
        # @blogkanagawaemotions = @blogkanagawas.joins(:blog_feelings).select('blog_feelings.emotion_id')
        @blogkanagawaemotions = @blogkanagawas.joins(:blog_feelings).select('blogs.*,blog_feelings.emotion_id')
        
        # @blogkanagawadatas = @blogkanagawaemotions.order('emotion_id DESC').limit(1).count(:emotion_id)
    
        # @blogkanagawaemotions = @blogkanagawas.joins(:blog_feelings).order('count_blogfeelings.emotion_id DESC').limit(1).count(:emotion_id).select('blog_feelings.emotion_id')
        
    end
    
    def new
        @blog = Blog.new
        @emotions = Emotion.all
        @blog.blog_feelings.build
        @themes = Theme.all
        @blog.blog_topics.build
        @blog_photo = @blog.blog_photos.build
        @blog_image = @blog.blog_images.build
    end
    
    def show
        @blog = Blog.find(params[:id])
        @like = Like.new
        @blog_photos = @blog.blog_photos.all
        @blog_images = @blog.blog_images.all
    end
    
    def create
        # Blog.create(blog_params)
        @blog = Blog.new(blog_params)
        
            respond_to do |format|
                if params[:blog_photos]==nil && params[:blog_images]==nil && @blog.save
                   @blog_image = @blog.blog_images.create!(:image => 'edit-24px.png')   #何故かいれておかないとimage_uploader.rbのdefault画像機能が動作しない。
                   @blog_photo = @blog.blog_photos.create!(:photo => 'edit-24px.png')   #何故かいれておかないとimage_uploader.rbのdefault画像機能が動作しない。
                format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                
                elsif params[:blog_photos]==nil && params[:blog_images]!=nil && @blog.save
                   @blog_photo = @blog.blog_photos.create!(:photo => 'edit-24px.png')   #何故かいれておかないとimage_uploader.rbのdefault画像機能が動作しない。
                  params[:blog_images]['image'].each do |b|
                   @blog_image = @blog.blog_images.create!(:image => b)
                  end
                format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                    
                elsif params[:blog_photos]!=nil && params[:blog_images]==nil && @blog.save
                   @blog_image = @blog.blog_images.create!(:image => 'edit-24px.png')   #何故かいれておかないとimage_uploader.rbのdefault画像機能が動作しない。
                  params[:blog_photos]['photo'].each do |a|
                   @blog_photo = @blog.blog_photos.create!(:photo => a)
                  end
                format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                
                elsif @blog.save
                  params[:blog_photos]['photo'].each do |a|
                   @blog_photo = @blog.blog_photos.create!(:photo => a)
                  end
                  params[:blog_images]['image'].each do |b|
                   @blog_image = @blog.blog_images.create!(:image => b)
                  end
                format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                
                else
                format.html { render 'blogs/new', notice: 'Item was not created.' }
                end
            end
       
    end
    
    def destroy
       blog = Blog.find(params[:id])
       if blog.user_id == current_user.id
           blog.destroy
       end
    end
    
    def edit
        @blog = Blog.find(params[:id])
        
    end
    
    def update
        # blog = Blog.find(params[:id])
        # if blog.user_id == current_user.id
        #     blog.update(blog_params)
        # end
        
        @blog = Blog.find(params[:id])
       
        #↓この辺いらないコマンドがありますな。
        respond_to do |format|
                if params[:blog_photos]==nil && params[:blog_images]==nil && @blog.update(blog_params)
                format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                
                elsif params[:blog_photos]==nil && params[:blog_images]!=nil && @blog.update(blog_params)
                  params[:blog_images]['image'].each do |b|
                   @blog_image = @blog.blog_images.update(:image => b)
                  end
                format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                    
                elsif params[:blog_photos]!=nil && params[:blog_images]==nil && @blog.update(blog_params)
                  params[:blog_photos]['photo'].each do |a|
                   @blog_photo = @blog.blog_photos.update(:photo => a)
                  end
                format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                
                elsif @blog.update(blog_params)
                  params[:blog_photos]['photo'].each do |a|
                   @blog_photo = @blog.blog_photos.update(:photo => a)
                  end
                  params[:blog_images]['image'].each do |b|
                   @blog_image = @blog.blog_images.update(:image => b)
                  end
                format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                
                else
                format.html { redirect_to @blog, notice: 'Item was not created.' }
                end
        end
        #↓うまくいってた複数画像編集basic_ver変更前↓
        #  respond_to do |format|
        #         if params[:blog_photos]==nil && params[:blog_images]==nil  && @blog.update(blog_params)
        #         format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                
        #         elsif @blog.update(blog_params)
        #           params[:blog_photos]['photo'].each do |a|
        #           @blog_photo = @blog.blog_photos.update(:photo => a)
        #           end
        #           params[:blog_images]['image'].each do |b|
        #           @blog_image = @blog.blog_images.update(:image => b)
        #           end
        #         format.html { redirect_to @blog, notice: 'Item was successfully created.' }
                
        #         else
        #         format.html { redirect_to @blog, notice: 'Item was not created.' }
        #         end
        #     end
        
    end
    
    # def search
    #     @blogs = Blog.where('title LIKE(?)', "%#{params[:keyword]}%")
    # end
    
    def search
        # @blogs = Blog.order("created_at DESC").page(params[:page]).per(5)
        
        @blogs = Blog.where('title LIKE(?)', "%#{params[:keyword]}%") #←これいる？
        @q = Blog.published.order(excellent: :desc).search(search_params)
        params.require(:q).permit(:title_cont)   #:qオブジェクトを指定し、さらに:qオブジェクトの中に定義された:title_contキーを指定している
        @bloges = @q.result.includes(:emotions,:themes)
    end
    
    private
    def search_params
        params.require(:q).permit!
    end
    
    def blog_params
        params.require(:blog).permit(:user_name, :title, :text, :status, blog_photos_attributes: [:id, :blog_id, :photo], blog_images_attributes: [:id, :blog_id, :image], emotion_ids: [], theme_ids: []).merge(user_id: current_user.id)
    end
    
    def move_to_index
       
           redirect_to  '/' unless user_signed_in?
    
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<!--<div class="mypage">-->
<!--    <div class="mypage_contents">-->
<!--                    <% if user_signed_in? && current_user.id == blog.user_id %>-->
<!--                        <%= link_to '編集しちゃおう', "/blogs/#{blog.id}/edit", method: :get %>-->
<!--                        <%= link_to '削除しちゃおう', "/blogs/#{blog.id}", method: :delete %>-->
<!--                        <%= link_to '詳細!', "/blogs/#{blog.id}", method: :get %>-->
<!--                    <% end %>-->
<!--              <%= simple_format(blog.title) %>-->
<!--              <%= simple_format(blog.text) %>-->
<!--    </div>-->
<!--</div>-->

<!-- ここから下が新マイページ2020ver -->
      <!--<% if user_signed_in? && current_user.id == blog.user_id %>-->
      <!--<div class="mypage-blog">-->
      <!--  <h2 class="mypage-content-title"><%= simple_format(blog.title) %></h2>-->
      <!--  <p class="mypage-content-paragraph"><%= simple_format(blog.text) %></p>-->
      <!--  <div class="mypage-blog-detail-block">-->
      <!--    <a href="#" class="w-button"><%= link_to '編集しちゃおう', "/blogs/#{blog.id}/edit", method: :get %></a>-->
      <!--    <a href="#" class="w-button"><%= link_to '削除しちゃおう', "/blogs/#{blog.id}", method: :delete %></a>-->
      <!--    <a href="#" class="w-button"><%= link_to '詳細!', "/blogs/#{blog.id}", method: :get %></a>-->
      <!--  </div>-->
      <!--</div>-->
      <!--<% end %>-->
<!-- ここから上が新マイページ2020ver -->

<!-- ここから下が新マイページ2020ver new -->
      <!--<% if user_signed_in? && current_user.id == blog.user_id %>-->
      <!--<div class="div-block-26">-->
      <!--  <h2 class="heading-23"><%= simple_format(blog.title) %></h2>-->
      <!--  <p class="paragraph-6"><%= blog.text %></p>-->
      <!--  <div class="div-block-27">-->
          <!--<a href="#" class="w-button"><%= link_to '編集しちゃおう', "/blogs/#{blog.id}/edit", method: :get %></a>-->
          <!--<a href="#" class="w-button"><%= link_to '削除しちゃおう', "/blogs/#{blog.id}", method: :delete%></a>-->
          <!--<a href="#" class="w-button"><%= link_to '詳細!', "/blogs/#{blog.id}", method: :get %></a>-->
      <!--    <%= link_to '編集しちゃおう', "/blogs/#{blog.id}/edit", method: :get %>-->
      <!--    <%= link_to '削除しちゃおう', "/blogs/#{blog.id}", method: :delete %>-->
      <!--    <%= link_to '詳細!', "/blogs/#{blog.id}", method: :get %>-->
      <!--  </div>-->
      <!--</div>-->
      <!--<% end %>-->
<!-- ここから上が新マイページ2020ver new -->

<!-- ここから下が新マイページ20201108 PCver new -->
  <div class="pc_area">
      <% if user_signed_in? && current_user.id == blog.user_id %>
      <div class="div-for-blog">
      <h2 class="title-blog"><%= simple_format(blog.title) %></h2>
      <p class="paragraph-blog"><%= blog.text %></p>
      <div class="details-sec">
        <%= link_to("/blogs/#{blog.id}", method: :get) do %>
        <div class="detail-butt">
          <div class="detail-photo"></div>
          <div class="detail-word">
            <div class="tb-detail">詳細!</div>
          </div>
        </div>
        <% end %>
        <%= link_to("/blogs/#{blog.id}", method: :delete) do %>
        <div class="delete-butt">
          <div class="delete-photo"></div>
          <div class="delete-word">
            <div class="deleted-word">削除!</div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
<!-- ここから上が新マイページ20201108 PCver new -->

<!-- ここから下が新マイページ20210107 Smartphonever new -->
<div class="phone_area">
    <% if user_signed_in? && current_user.id == blog.user_id %>
        <%= link_to("/blogs/#{blog.id}", method: :get) do %>
          <div class="sp_mypage_blog">
              <h4 class="sp_mypage_blog_title"><%= simple_format(blog.title) %></h4>
          </div>
        <% end %>
    <% end %>
</div>
<!-- ここから上が新マイページ20210107 Smartphonever new -->

app/views/blogs/adminpage.html.erb
<div class="pc_area">
  <div class="sec-for-timeline-body">
       PV数取得のために設置
     <% @blogs.each do |t| %>
          <p><%= t.id%><%=  t.impressions_count %></p>
          
      <% end %>
      <p>Total:<%= Blog.all.sum(:impressions_count) %></p>
     
  </div>
</div>

app/views/blogs/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      ブログの投稿が完了しました。
    </h3>
    <!--<a class="btn" href="/blogs">投稿一覧へ戻る</a>-->
    <li><%= link_to "マイページへ戻る", mypage_user_path(current_user) %></li>
  </div>
</div>

app/views/blogs/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      ブログ削除が完了しました。
    </h3>
    <%= link_to "投稿一覧へ戻る", mypage_user_path(current_user) %>
  </div>

app/views/blogs/detailpage.html.erb
<!-- ここからタイムラインブログ詳細2019はじまり! -->
<!--<div class="contents row">-->
    
<!--    <% if user_signed_in? && current_user.id == @blog.user_id %>-->
<!--      <div class="more">-->
<!--        <span><%= image_tag 'arrow_top.png' %></span>-->
       
<!--      </div>-->
<!--    <% end %>-->
<!--    <%= simple_format(@blog.title) %>-->
<!--    <%= simple_format(@blog.text) %>-->
<!--    <%= simple_format(@blog.user.nickname) %>-->
<!--    <%= simple_format(@blog.user.selfintroduction) %>-->
    
<!--    <% @blog_photos.each do |p| %>-->
<!--      <%= image_tag p.photo_url, style: "max-width: 200px; max-height: 200px" %>-->
      
<!--    <% end %>-->
    
<!--     <% if current_user.already_liked?(@blog) %>-->
<!--  <%= button_to 'いいねを取り消す', blog_like_path(@blog), method: :delete %>-->
<!--<% else %>-->
<!--  <%= button_to 'いいね', blog_likes_path(@blog) %>-->
<!--<% end %>-->
<!--<h3>いいね件数: <%= @blog.likes.count %></h3>-->
    
<!--    <span class="name">-->
<!--      <a href="/users/<%= @blog.user.id %>">-->
<!--        <span>投稿者</span><%= @blog.user.nickname %>-->
<!--      </a>-->
<!--    </span>-->
 
<!--</div>-->

<!-- ここまでタイムラインブログ詳細2019おわり! -->


<!-- ここからタイムラインブログ詳細2019はじまり! -->

  <!--<div class="section-29">-->
  <!--  <% if user_signed_in? && current_user.id == @blog.user_id %>-->
  <!--  <% end %>-->
  <!--  <div class="div-block-38">-->
  <!--    <div class="div-block-40">-->
  <!--      <h1><%= simple_format(@blog.title) %></h1>-->
  <!--    </div>-->
  <!--    <div class="div-block-41">-->
  <!--      <p class="paragraph-9"><%= @blog.text %></p>-->
  <!--    </div>-->
  <!--    <div class="div-block-118">-->
  <!--      <% @blog_photos.each do |p| %>-->
  <!--      <div class="div-block-119">-->
  <!--          <%= image_tag p.photo_url, style: "max-width: 200px; max-height: 200px" %>-->
  <!--      </div>-->
  <!--      <% end %>-->
  <!--    </div>-->
  <!--    <div class="div-block-121">-->
  <!--      <div class="text-block-45">作成日時: 2020年2月20日</div>-->
  <!--    </div>-->
  <!--    <div class="div-block-42">-->
  <!--      <% if current_user.already_liked?(@blog) %>-->
  <!--        <a class="button-6 w-button"><%= button_to 'いいねを取り消す', blog_like_path(@blog), method: :delete %></a>-->
  <!--      <% else %>-->
  <!--        <a class="button-6 w-button"><%= button_to 'いいね', blog_likes_path(@blog) %></a>-->
  <!--      <% end %>-->
  <!--      <div class="text-block-46">いいね件数: <%= @blog.likes.count %></div>-->
  <!--    </div>-->
  <!--    <div class="div-block-122">-->
  <!--      <div>投稿者: </div>-->
  <!--      <div><%= simple_format(@blog.user.nickname) %></div>-->
  <!--    </div>-->
  <!--  </div>-->
  <!--  <div class="div-block-44">-->
  <!--    <div class="div-block-124">-->
  <!--      <h1 class="heading-28">自己紹介</h1>-->
  <!--    </div>-->
  <!--    <div class="div-block-123">-->
  <!--      <div><%= simple_format(@blog.user.selfintroduction) %></div>-->
  <!--    </div>-->
  <!--  </div>-->
  <!--</div>-->
<!-- ここまでタイムラインブログ詳細2019おわり! -->


<!-- ここからタイムラインブログ詳細20201109 PC ver はじまり! -->
<div class="pc_area">
  <div class="section-blog-show">
    <% if user_signed_in? && current_user.id == @blog.user_id %>
     <% end %>
      <div class="blog-show">
        <div class="div-blog-show-title">
          <h2 class="blog-show-title-word"><%= simple_format(@blog.title) %></h2>
        </div>
        <p class="blog-show-sentence"><%= @blog.text %></p>
        <div class="blog-show-photo">
          <% @blog_photos.each do |p| %>
          <div class="blog-show-photo-left"><%= image_tag p.photo_url, style: "max-width: 420px; max-height: 300px" %></div>
          <!--<div class="blog-show-photo-right">%= image_tag p.photo_url, style: "max-width: 200px; max-height: 200px" %></div>-->
          <% end %>
          <% @blog_images.each do |q| %>
          <div class="blog-show-photo-right"><%= image_tag q.image_url, style: "max-width: 420px; max-height: 300px" %></div>
          <% end %>
        </div>
        <div class="blog-show-detail">
          <div class="blog-show-nickname">
            <div class="blog-show-left-nickname">投稿者:</div>
            <div class="blog-show-right-nickname"><%= simple_format(@blog.user.nickname) %></div>
          </div>
          <div class="blog-show-made-date">
            <div class="blog-show-left-date">作成日:</div>
            <div class="blog-show-right-date"><%= @blog.created_at %></div>
          </div>
        </div>
        <div class="blog-show-readit">
          <div class="blog-show-readit-area">
            <div class="readit-area-text">
              <% if current_user.already_liked?(@blog) %>
                  <%= button_to '読んだよ！を取り消す', blog_like_path(@blog), method: :delete %>
              <% else %>
                  <%= button_to '読んだよ！', blog_likes_path(@blog) %>
              <% end %>
            </div>
          </div>
          <div class="readit-block">
            <div class="readit-block-word">読んだよ！件数:</div>
            <div class="readit-block-var"><%= @blog.likes.count %></div>
          </div>
        </div>
      </div>
      <div class="self-show">
        <div class="welf-show-title">
          <h2 class="self-show-heading">Heading</h2>
        </div>
        <p class="self-show-paragraph"><%= simple_format(@blog.user.selfintroduction) %></p>
      </div>
      
      <div class="self-show">
        <% if current_user && current_user.commenter == "normal" && current_user.id != @blog.user_id%>
          <%= form_tag("/blogs/#{@blog.id}/comments", method: :post) do %>
            <textarea name="text" placeholder="コメントする" rows="2" cols="30"></textarea>
            <input type="submit" value="SEND">
          <% end %>
        <% end %>
      </div>
    
    <div class="self-show">
        <% if @comments %>
          <% @comments.each do |comment| %>
            <% if (current_user && current_user.id == @blog.user_id) || (current_user && current_user.id == comment.user_id) %>
              <%= link_to 'コメントを削除する', blog_comment_path(@blog, comment), confirm: 'Are you sure?', method: :delete %>
            <% end %>
          <p><%= comment.text %></p>
          <% end %>
        <% end %>
    </div>
      
  </div>
</div>
<!-- ここまでタイムラインブログ詳細20201109 PC ver おわり! -->

<!-- ここからタイムラインブログ詳細20210109 Smartphone ver はじまり! -->
<div class="phone_area">
  <div class="sp_blogdetail_mainbody">
    <% if user_signed_in? && current_user.id == @blog.user_id %>
    <% end %>
    <div class="sp_blogdetail_blog">
      <h4 class="sp_blogdetail_blog_heading"><%= simple_format(@blog.title) %></h4>
      <div class="sp_blogdetail_blog_sentence"><%= @blog.text %></div>
      <div class="sp_blogdetail_images">
        <div class="sp_blogdetail_image_top"></div>
        <div class="sp_blogdetail_image_bottom"></div>
      </div>
      <div class="sp_blogshow_writer">
        <div class="sp_blogshow_writer_word">投稿者:</div>
        <div class="sp_blogshow_writer_var"><%= simple_format(@blog.user.nickname) %></div>
      </div>
      <div class="sp_blogshow_date">
        <div class="sp_blogshow_date_word">作成日:</div>
        <div class="sp_blogshow_date_word_var"><%= @blog.created_at %></div>
      </div>
      <div class="sp_blogshow_readit">
        <div class="sp_readit_word">
          <div class="sp_readit_text">
            <% if current_user.already_liked?(@blog) %>
                  <%= button_to '読んだよ！を取り消す', blog_like_path(@blog), method: :delete %>
            <% else %>
                  <%= button_to '読んだよ！', blog_likes_path(@blog) %>
            <% end %>
          </div>
        </div>
        <div class="sp_readit_real">
          <div class="sp_readit_realword">読んだよ!件数:</div>
          <div class="sp_readit_realvar"><%= @blog.likes.count %></div>
        </div>
      </div>
    </div>
    <div class="sp_readit_inroduction">
      <h4 class="sp_readit_introduction_heading">Heading</h4>
      <div class="sp_readit_introduction_sentence"><%= simple_format(@blog.user.selfintroduction) %></div>
    </div>
    
  </div>
</div>
<!-- ここまでタイムラインブログ詳細20210109 Smartphone ver おわり! -->

app/views/blogs/index.html.erb
<div class="contents row" >
  <% @blogs.each do |blog| %>
    <div class="content_post">
      <%= simple_format(blog.text) %>
      <span class="name"><%= blog.user_name %></span>
    </div>
  <% end %>
  <%= paginate(@blogs) %>
</div>

app/views/blogs/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <%= link_to "投稿一覧へ戻っちゃおう", mypage_user_path(current_user) %>
  </div>
</div>