config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # devise_for :users //before
    devise_for :users, controllers: {
      confirmations: "users/confirmations",
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      unlocks: "users/unlocks"
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'top#index'
    resources :users, only: [:show, :edit, :update] do
      member do
        get 'mypage'
      end
    end
    resources :blogs,  only: [:index, :new, :create, :destroy, :edit, :update, :show] do
      collection do
        get 'search'
      end
      collection do
        get 'topmap'
      end
      collection do
        get 'adminpage'
      end
      member do
        get 'detailpage'
      end
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
    resources :journals, only: [:new, :create, :destroy, :edit, :update, :show]
    resources :notifications, only: [:create, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
    default_scope -> { order(created_at: :desc) }
    belongs_to :blog, optional: true
    belongs_to :comment, optional: true
    belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
    belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    def create
        
        @notifications = current_user.passive_notifications.includes(:blog)
        @notifications.where(checked: false).each do |notification|
            notification.update_attributes(checked: true)
        end
        
    end
    
    def destroy
        @notifications = current_user.passive_notifications.destroy_all
        redirect_to mypage_user_path(current_user)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<div class="pc_area">
    <!--% visitor = notification.visitor %>-->
    <!--% visited = notification.visited %>-->
    
    <div class="user-view clearfix ">
      <% if notification.action == 'like' then %>
      <p><%=link_to 'あなたのドラマ', notification.blog %>が読まれました</p>
      
      <% elsif notification.action == 'comment' then %>
      <p><%=link_to 'あなたのドラマ', notification.blog %>にコメントがありました</p>
      <% end %>
      <%= link_to 'コメントを削除する', notification_path(@blog, notification), confirm: 'Are you sure?', method: :delete %>
      
      <!--% case @notifications.action when "like" %>-->
      <!--<p>あなたのドラマが読まれました</p>-->
      <!--% when "comment" %>-->
      <!--<p>あなたに文章修正コメントがありました</p>-->
      <!--% end %>-->
    </div>
</div>