config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # devise_for :users //before
    devise_for :users, controllers: {
      confirmations: "users/confirmations",
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      unlocks: "users/unlocks"
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'top#index'
    resources :users, only: [:show, :edit, :update] do
      member do
        get 'mypage'
      end
    end
    resources :blogs,  only: [:index, :new, :create, :destroy, :edit, :update, :show] do
      collection do
        get 'search'
      end
      collection do
        get 'topmap'
      end
      collection do
        get 'adminpage'
      end
      member do
        get 'detailpage'
      end
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
    resources :journals, only: [:new, :create, :destroy, :edit, :update, :show]
    resources :notifications, only: [:create, :destroy]
end

app/views/common/_header.html.erb
<!--<header class="header">-->
<!--      <div class="header_main"><h1 class="grid-6"><a href="/">Senblog</a></h1></div>-->
<!--      <div class="header__bar">-->

<!--<% if user_signed_in? %>-->
  <!--<div class='navbar navbar-default navbar-fixed-top'>-->
  <!--  <div class='container'>-->
      <!--<button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>-->
      <!--  <span class='icon-bar'></span>-->
      <!--  <span class='icon-bar'></span>-->
      <!--  <span class='icon-bar'></span>-->
      <!--</button>-->
      <!--<%= link_to root_path, :class => 'navbar-brand' do %>-->
      <!--  <%= image_tag 'logo.png' %> <small class='hidden-xs hidden-sm'>ヘッダーだよ！</small>-->
      <!--<% end %>-->
<!--      <div class='nav__bar'>-->
<!--        <ul class='options'>-->
<!--          <li><%= link_to 'Timeline', root_path %></li>-->
<!--          <li><%= link_to "マイページ", mypage_user_path(current_user) %></li>-->
<!--          <li><%= link_to "ブログ投稿", new_blog_path %></li>-->
<!--          <li><%= link_to "日記を書く", new_journal_path %></li>-->
<!--          <li><%= link_to "プロフィール", user_path(current_user) %></li>-->
<!--          <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>-->
<!--          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>-->
          
          <!--User after learning Javascript-->
          <!--<li class="dropdown">-->
          <!--     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">投稿する <span class="caret"></span></a>-->
          <!--     <ul class="dropdown-menu" role="menu">-->
          <!--          <li><%= link_to "ブログを投稿する", new_blog_path %></li>-->
          <!--          <li><%= link_to "日記を書き込む", new_journal_path %></li>-->
          <!--     </ul>-->
        
          <!--<li class='dropdown'>-->
          <!--   <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>アカウント <span class='caret'></span></a>-->
          <!--  <ul class='dropdown-menu' role='menu'>-->
          <!--    <li><%= link_to "プロフィール", user_path(current_user) %></li>-->
          <!--    <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>-->
          <!--    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>-->
          <!--  </ul>-->
          <!--</li>-->
<!--        </ul>-->
<!--      </div>-->
  <!--  </div>-->
  <!--</div>-->
<!--<% end %>-->
<!-- </div>-->
<!--        <%= bootstrap_flash %>-->
<!--</header>-->


<!-- ここから下が新ヘッダー2019ver -->
<!--<div>-->
<!--  <% if user_signed_in? %>-->
<!--<div class="section-13">-->
<!--    <div class="div-block-17">-->
<!--      <h1><a href="/">Sen</a></h1>-->
<!--    </div>-->
<!--    <div class="div-block-18">-->
<!--      <div class="text-block-13"><%= link_to 'Timeline', root_path %></div>-->
<!--        <div class="text-block-15"><%= link_to "マイページ", mypage_user_path(current_user) %></div>-->
<!--        <div class="text-block-15"><%= link_to "ブログ投稿", new_blog_path %></div>-->
<!--        <div class="text-block-15"><%= link_to "日記を書く", new_journal_path %></div>-->
<!--        <div class="text-block-15"><%= link_to "プロフィール", user_path(current_user) %></div>-->
<!--        <div class="text-block-15"><%= link_to "プロフィール編集", edit_user_path(current_user) %></div>-->
<!--        <div class="text-block-15"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></div>-->
<!--    </div>-->
<!--  </div>-->
<!--  <% end %>  -->
<!--  <%= bootstrap_flash %>-->
<!--</div>-->
  <!-- ここから上が新ヘッダー2019ver -->
  
<!-- ここから下が新ヘッダー2020ver -->
<!--<div>-->
<!--  <% if user_signed_in? %>-->
<!--<div class="header-class">-->
<!--    <div class="header-class-title">-->
<!--      <h1 class="header-title"><a href="/">Arkchive</a></h1>-->
<!--    </div>-->
    
<!--    <div class="header-class-menu">-->
<!--      <div data-collapse="medium" data-animation="default" data-duration="400" class="navbar-menu w-nav">-->
<!--        <div class="navigation w-container">-->
<!--          <nav role="navigation" class="navigation-menu w-nav-menu">-->
<!--            <p><a href="#" class="nav-link-menu w-nav-link"><%= link_to 'タイムライン', root_path %></a></p>-->
<!--            <p><a href="#" class="nav-link-menu w-nav-link"><%= link_to "マイページ", mypage_user_path(current_user) %></a></p>-->
<!--            <p><a href="#" class="nav-link-menu w-nav-link"><%= link_to "ブログ投稿", new_blog_path %></a></p>-->
<!--            <p><a href="#" class="nav-link-menu w-nav-link"><%= link_to "日記を書く", new_journal_path %></a></p>-->
<!--            <p><a href="#" class="nav-link-menu w-nav-link"><%= link_to "プロフィール", user_path(current_user) %></a></p>-->
<!--            <p><a href="#" class="nav-link-menu w-nav-link"><%= link_to "プロフィール編集", edit_user_path(current_user) %></a></p>-->
<!--            <p><a href="#" class="nav-link-menu w-nav-link"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></a></p>-->
<!--          </nav>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--</div>-->
<!--  <% end %>  -->
<!--  <%= bootstrap_flash %>-->
<!--</div>-->
<!-- ここから上が新ヘッダー2020ver -->


<!-- ここから下が新ヘッダー20201107 PCver -->
<div class="pc_area">
  <div>
    <% if user_signed_in? %>
    <div class="section-for-header">
      <div class="adjust-section-header">
        <h1 class="heading-header"><a href="/">Arkchive</a></h1>
      </div>
      <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="navbar-for-header w-nav">
        <div class="w-container">
          <nav role="navigation" class="nav-menu-header w-nav-menu">
            <%= link_to(root_path, data: {"turbolinks" => false}) do %>
            <div class="div-timeline">
              <div class="div-nav-image-1"></div>
              <div class="tb-timeline">タイムライン</div>
               <!--%= link_to('タイムライン', root_path, {class: "tl"}) %>-->
            </div>
            <% end %>
            <%= link_to(mypage_user_path(current_user)) do %>
            <div class="div-mypage">
              <div class="div-nav-image-2"></div>
              <div class="tb-mypage">マイページ</div>
            </div>
            <% end %>
            <% if (current_user.blogger == "general") && (current_user.blogs.count <= 100) %>
            <%= link_to(new_blog_path, data: {"turbolinks" => false}) do %>
            <div class="div-write-blog">
              <div class="div-nav-image-3"></div>
              <div class="tb-write-blog">感想文投稿<%=  %></div>
            </div>
            <% end %>
            <% end %>
            <%= link_to(topmap_blogs_path) do %>
            <div class="div-write-journal">
              <div class="div-nav-image-4"></div>
              <div class="tb-write-journal">マップを見る</div>
            </div>
            <% end %>
            <%= link_to(user_path(current_user)) do %>
            <div class="div-go-profile">
              <div class="div-nav-image-5"></div>
              <div class="tb-profile">プロフィール</div>
            </div>
            <% end %>
            <%= link_to(destroy_user_session_path, method: :delete) do %>
            <div class="div-log-out">
              <div class="div-nav-image-6"></div>
              <div class="tb-logout">ログアウト</div>
            </div>
            <% end %>
            
          </nav>
          <div class="w-nav-button">
            <div class="w-icon-nav-menu"></div>
          </div>
        </div>
      </div>
    </div>
    <% else %>
    <div class="section-for-header">
      <div class="adjust-section-header">
        <h1 class="heading-header"><a href="/">Arkchive</a></h1>
      </div>
      <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="navbar-for-header w-nav">
        <div class="w-container">
          <nav role="navigation" class="nav-menu-header w-nav-menu">
            <%= link_to(root_path, data: {"turbolinks" => false}) do %>
            <div class="div-timeline">
              <div class="div-nav-image-1"></div>
              <div class="tb-timeline">タイムライン</div>
               <!--%= link_to('タイムライン', root_path, {class: "tl"}) %>-->
            </div>
            <% end %>
            <%= link_to(new_user_session_path, method: :get) do %>
            <div class="div-log-out">
              <div class="div-nav-image-6"></div>
              <div class="tb-logout">ログイン</div>
            </div>
            <% end %>
            
            
          </nav>
          <div class="w-nav-button">
            <div class="w-icon-nav-menu"></div>
          </div>
        </div>
      </div>
    </div>
    <% end %>  
    <%= bootstrap_flash %>
  </div>
</div>
<!-- ここから上が新ヘッダー20201107 PCver -->

<!-- ここから下が新ヘッダー20210107 Smartphone ver -->
<div class="phone_area">
  <div class="sp_header">
    <% if user_signed_in? %>
        <div class="sp_tab_white">
          <h2 class="sp_header_title"><a href="/">Arkchive</a></h2>
          <div class="sp_droptab"></div>
          <div class="sp_drop_tab_section">
            <%= link_to(root_path) do %>
              <div class="sp_drop_tab_timeline">
                <div class="sp_droptab_timeline">タイムライン</div>
              </div>
            <% end %>
            <%= link_to(mypage_user_path(current_user)) do %>
              <div class="sp_drop_tab_mypage">
                <div class="sp_droptab_mypage">マイページ</div>
              </div>
            <% end %>
            <%= link_to(new_blog_path) do %>
              <div class="sp_drop_tab_blog">
                <div class="sp_droptab_blog">感想文投稿</div>
              </div>
            <% end %>
            <%= link_to(new_journal_path) do %>
              <div class="sp_drop_tab_journal">
                <div class="sp_droptab_journal">下書きを書く</div>
              </div>
            <% end %>
            <%= link_to(user_path(current_user)) do %>
              <div class="sp_drop_tab_profile">
                <div class="sp_droptab_profile">プロフィール</div>
              </div>
            <% end %>
            <%= link_to(destroy_user_session_path, method: :delete) do %>
              <div class="sp_drop_tab_logout">
                <div class="sp_droptab_logout">ログアウト</div>
              </div>
            <% end %>
              <div class="sp_drop_tab_close">
                <div class="sp_drop_tab_close_arrow"></div>
              </div>
          </div>
        </div>
    <% end %>  
    <%= bootstrap_flash %>
  </div>
</div>
<!-- ここから上が新ヘッダー20210107 Smartphone ver -->